### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by marchon** [AntonKueltz/fastecdsa#8]
would you like me to help you track down the problems with your package setup? 

root@ubuntu:~/opencl/fastecdsa/fastecdsa# python setup.py test
running test
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/marchon/opencl/fastecdsa/fastecdsa/fastecdsa/test.py", line 5, in <module>
    from .curve import P192, P224, P256, P384, P521, secp256k1
  File "fastecdsa/curve.py", line 1, in <module>
    from fastecdsa import curvemath
ImportError: cannot import name curvemath

**Comment by AntonKueltz** [comment]
How did you install the package? `curvemath` is one of the C modules that needs to be built before the package can be used, so if you cloned the repo and tried to run test before building the C extensions you'll get this error.
